// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { env, defineConfig } from "prisma/config";
import { config } from "dotenv"
import { resolve } from "path"

config({ path: resolve(__dirname, ".env.local") })

const databaseUrl = process.env.DATABASE_URL

if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set in .env.local")
}

export default defineConfig ({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
